//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunicationModule.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommunicationModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 获取通讯日志失败，数据库句柄为空或没有日志信息 的本地化字符串。
        /// </summary>
        internal static string strCommLogListError {
            get {
                return ResourceManager.GetString("strCommLogListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口启动失败 的本地化字符串。
        /// </summary>
        internal static string strCOMStartError {
            get {
                return ResourceManager.GetString("strCOMStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接建立 的本地化字符串。
        /// </summary>
        internal static string strConnected {
            get {
                return ResourceManager.GetString("strConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接端口{0}，设备ID为{1}的客户已连接，连接时间为{2} 的本地化字符串。
        /// </summary>
        internal static string strConnectedAlarmContent {
            get {
                return ResourceManager.GetString("strConnectedAlarmContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接失败 的本地化字符串。
        /// </summary>
        internal static string strDatabaseConnectError {
            get {
                return ResourceManager.GetString("strDatabaseConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备传入设备号为空 的本地化字符串。
        /// </summary>
        internal static string strDeviceIDError {
            get {
                return ResourceManager.GetString("strDeviceIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接断开 的本地化字符串。
        /// </summary>
        internal static string strDisconnected {
            get {
                return ResourceManager.GetString("strDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接端口{0}，设备ID为{1}的客户已断开，断开时间为{2} 的本地化字符串。
        /// </summary>
        internal static string strDisconnectedAlarmContent {
            get {
                return ResourceManager.GetString("strDisconnectedAlarmContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯列表为空，没有任何通讯被建立 的本地化字符串。
        /// </summary>
        internal static string strListCommStationEmpty {
            get {
                return ResourceManager.GetString("strListCommStationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示列表为空，当前没有通讯被启动 的本地化字符串。
        /// </summary>
        internal static string strListShowEmpty {
            get {
                return ResourceManager.GetString("strListShowEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站点表为空，没有要重置的信息 的本地化字符串。
        /// </summary>
        internal static string strListStationEmpty {
            get {
                return ResourceManager.GetString("strListStationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站点信息表为空 的本地化字符串。
        /// </summary>
        internal static string strListUDPLinkerEmpty {
            get {
                return ResourceManager.GetString("strListUDPLinkerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数传入为null 的本地化字符串。
        /// </summary>
        internal static string strNullParameterError {
            get {
                return ResourceManager.GetString("strNullParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取联系人电话失败，数据库句柄为空或者没有配置联系人 的本地化字符串。
        /// </summary>
        internal static string strPhoneListError {
            get {
                return ResourceManager.GetString("strPhoneListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 携带ntrip协议的对象为null 的本地化字符串。
        /// </summary>
        internal static string strProtocalObjectError {
            get {
                return ResourceManager.GetString("strProtocalObjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取表信息失败 的本地化字符串。
        /// </summary>
        internal static string strReadTableFailure {
            get {
                return ResourceManager.GetString("strReadTableFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多端口通讯模式，确保单个采集设备连接该端口 的本地化字符串。
        /// </summary>
        internal static string strRemark {
            get {
                return ResourceManager.GetString("strRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备{0}在该时间点前曾异常终止！断电或别的原因导致? 的本地化字符串。
        /// </summary>
        internal static string strStationDisposeException {
            get {
                return ResourceManager.GetString("strStationDisposeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StatusEventHandler句柄为空，无法将底层信息返回给界面显示 的本地化字符串。
        /// </summary>
        internal static string strStatusEventHandlerError {
            get {
                return ResourceManager.GetString("strStatusEventHandlerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取表信息失败，可确认表是否存在 的本地化字符串。
        /// </summary>
        internal static string strTableNotExistError {
            get {
                return ResourceManager.GetString("strTableNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据端连接建立 的本地化字符串。
        /// </summary>
        internal static string strUDPDstConnected {
            get {
                return ResourceManager.GetString("strUDPDstConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据端连接断开 的本地化字符串。
        /// </summary>
        internal static string strUDPDstDisconnected {
            get {
                return ResourceManager.GetString("strUDPDstDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备端连接建立 的本地化字符串。
        /// </summary>
        internal static string strUDPSrcConnected {
            get {
                return ResourceManager.GetString("strUDPSrcConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备端连接断开 的本地化字符串。
        /// </summary>
        internal static string strUDPSrcDisconnected {
            get {
                return ResourceManager.GetString("strUDPSrcDisconnected", resourceCulture);
            }
        }
    }
}
